<a href="https://colab.research.google.com/github/Abdul-muizz/Abdul-Muizz.github.io/blob/main/60_The_Real_CNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import datetime
import pandas as pd
from sklearn import tree
import time
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn import svm
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
import numpy as np
from sklearn import preprocessing
import sklearn as sk
from sklearn.linear_model import LogisticRegression
import os
from sklearn.model_selection import train_test_split

from sklearn.linear_model import SGDClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline

from numpy import loadtxt
from keras.models import Sequential
from keras.layers import Dense

import numpy as np
import pandas as pd

from keras.models import Model, Sequential
from keras.callbacks import EarlyStopping, ModelCheckpoint
from keras.layers import Dense, Input, LSTM, Embedding, Dropout, Activation
from keras import utils as np_utils
#from keras.layers.merge import concatenate
#from keras.layers.normalization import BatchNormalization
from keras.preprocessing import sequence
from keras.preprocessing.text import Tokenizer
#from keras.preprocessing.sequence import pad_sequences
from keras.layers import Conv1D, MaxPooling1D, Flatten, Reshape
import matplotlib.pyplot as plt

#from keras.layers.wrappers import TimeDistributed

import keras
from sklearn import preprocessing
import tensorflow as tf
#from sklearn.metrics import plot_confusion_matrix
from sklearn.metrics import multilabel_confusion_matrix
from sklearn.metrics import confusion_matrix
from sklearn.ensemble import RandomForestClassifier

import imblearn
from imblearn.under_sampling import RandomUnderSampler

import random
import tensorflow as tf
from imblearn.over_sampling import SMOTE
from torch.utils.data import Dataset, DataLoader, WeightedRandomSampler
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torch
from sklearn.metrics import classification_report, cohen_kappa_score
from sklearn.metrics import precision_score, recall_score, f1_score

from google.colab import drive
drive.mount('/content/drive')
%cd /content/drive/MyDrive
!pwd

Mounted at /content/drive
/content/drive/MyDrive
/content/drive/MyDrive


In [ ]:
#code to get the paths of files in my drive
import os
for dirname, _, filenames in os.walk('/content/drive/MyDrive/'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/content/drive/MyDrive/Computer_Organization_Unit_4_JWFILES.pdf
/content/drive/MyDrive/COunit5_JWFILES.pdf
/content/drive/MyDrive/Computer_Organization_Unit_3_JWFILES.pdf
/content/drive/MyDrive/exchangeminmmax.c
/content/drive/MyDrive/KELANI ABDUL MUIZZ OLAMILEKAN ADMISSION LETTER (CSE).jpg
/content/drive/MyDrive/IMG-20170512-WA0020.jpg
/content/drive/MyDrive/ITN_T-hub.rar
/content/drive/MyDrive/The Failure List.pdf
/content/drive/MyDrive/img081.jpg
/content/drive/MyDrive/123.doc
/content/drive/MyDrive/Curriculum Vitae (2).pdf
/content/drive/MyDrive/Curriculum Vitae.pdf
/content/drive/MyDrive/Full page print.pdf
/content/drive/MyDrive/Task_1_Queries.sql
/content/drive/MyDrive/Task_2_Query.sql
/content/drive/MyDrive/Task_3_Query.sql
/content/drive/MyDrive/Task_4_Query.sql
/content/drive/MyDrive/Task_5_conf.txt
/content/drive/MyDrive/Task 1 response 1.ssmssqlproj
/content/drive/MyDrive/Task 1 response 2.ssmssln
/content/drive/MyDrive/Task 2 response.ssmssln
/content/drive/MyDrive/Task 3 

In [ ]:
# de1= pd.read_csv('/content/drive/MyDrive/USB-IDS Datasets/Hulk-Reqtimeout.csv')
# de2= pd.read_csv('/content/drive/MyDrive/USB-IDS Datasets/REGULAR.csv')
# de3= pd.read_csv('/content/drive/MyDrive/USB-IDS Datasets/TCPFlood-NoDefense.csv')
# de4= pd.read_csv('/content/drive/MyDrive/USB-IDS Datasets/TCPFlood-Reqtimeout.csv')
# de5= pd.read_csv('/content/drive/MyDrive/USB-IDS Datasets/TCPFlood-Evasive.csv')
# merge_data_2021= pd.concat([de1,de2,de3,de4,de5])
# merge_data_2021.to_csv('merge_data_2021.to_csv', index=False)

In [ ]:
#db1 = pd.read_csv('Monday-WorkingHours.csv', sep=',')
db2 = pd.read_csv('/content/drive/MyDrive/Revised_2021_Dataset.csv')
# db = pd.read_csv('/content/drive/MyDrive/USB-IDS Datasets/USB-IDS-1-VALIDATION.csv')
# db2_1 = db.iloc[:1000000]
# labels_to_keep = ['Hulk-Reqtimeout','BENIGN','TCPFlood-Evasive','Slowhttptest-NoDefense','Hulk-Evasive']
# db2 = db2_1[db2_1['Label'].isin(labels_to_keep)]
#db3 = pd.read_csv('Wednesday-workingHours.pcap_ISCX.csv', sep=',')
#db4 = pd.read_csv('Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv', sep=',')
#db4 = pd.read_csv('Thursday-WorkingHours.csv', sep=',')
#db5 = pd.read_csv('Friday-WorkingHours.csv', sep=',')
#db7 = pd.read_csv('Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv', sep=',')
#db8 = pd.read_csv('Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv', sep=',')
#full_db = pd.concat([db1, db2, db3, db4, db5, db6, db7, db8])

#print(full_db.shape, full_db[' Label'].value_counts())
#print(100*full_db[' Label'].value_counts(normalize=True))
print(db2.shape, db2['Label'].value_counts())
print(100*db2['Label'].value_counts(normalize=True))

(370067, 84) Hulk-Reqtimeout           142196
Hulk-Evasive              125744
BENIGN                     50716
TCPFlood-Evasive           50278
Slowhttptest-NoDefense      1133
Name: Label, dtype: int64
Hulk-Reqtimeout           38.424393
Hulk-Evasive              33.978712
BENIGN                    13.704545
TCPFlood-Evasive          13.586188
Slowhttptest-NoDefense     0.306161
Name: Label, dtype: float64


In [ ]:
db2.columns

Index(['Flow ID', 'Src IP', 'Src Port', 'Dst IP', 'Dst Port', 'Protocol',
       'Timestamp', 'Flow Duration', 'Total Fwd Packet', 'Total Bwd packets',
       'Total Length of Fwd Packet', 'Total Length of Bwd Packet',
       'Fwd Packet Length Max', 'Fwd Packet Length Min',
       'Fwd Packet Length Mean', 'Fwd Packet Length Std',
       'Bwd Packet Length Max', 'Bwd Packet Length Min',
       'Bwd Packet Length Mean', 'Bwd Packet Length Std', 'Flow Bytes/s',
       'Flow Packets/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max',
       'Flow IAT Min', 'Fwd IAT Total', 'Fwd IAT Mean', 'Fwd IAT Std',
       'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Total', 'Bwd IAT Mean',
       'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min', 'Fwd PSH Flags',
       'Bwd PSH Flags', 'Fwd URG Flags', 'Bwd URG Flags', 'Fwd Header Length',
       'Bwd Header Length', 'Fwd Packets/s', 'Bwd Packets/s',
       'Packet Length Min', 'Packet Length Max', 'Packet Length Mean',
       'Packet Length Std', 'Packet Len

In [ ]:
min_max_scaler = MinMaxScaler()
le = preprocessing.LabelEncoder()

# db = full_db (for now we are usind db2)
db = db2[~db2.isin([np.inf]).any(1)]
df = db
#df = pd.DataFrame(db)
#df.drop(['Flow ID'], axis = 1)
#df.drop(['Src IP'], axis = 1)
#df.drop(['Dst IP'], axis = 1)
#df.drop(['Timestamp'], axis = 1)
del df['Flow ID'], df['Src IP'], df['Dst IP'], df['Timestamp']
#print(df.dtypes)
X, y = df.iloc[:, :-1], df.iloc[:, -1]

trainX1, testX, trainY1, testY = train_test_split(X, y, test_size=0.4, random_state=42)

trainY1=le.fit_transform(trainY1.to_numpy()).astype('int')
testY=le.fit_transform(testY.to_numpy()).astype('int')

trainX1 = min_max_scaler.fit_transform(trainX1)
testX = min_max_scaler.fit_transform(testX)

print(trainX1.shape, trainY1.shape, testX.shape, testY.shape)
trainX, trainY = trainX1, trainY1

X1 = np.reshape(trainX, (trainX.shape[0], trainX.shape[1], 1))
X2 = np.reshape(testX, (testX.shape[0], testX.shape[1], 1))
Y1 = np.reshape(trainY, (trainY.shape[0], 1))
Y1 = tf.keras.utils.to_categorical(Y1)
Y2 = np.reshape(testY, (testY.shape[0], 1))
Y2 = tf.keras.utils.to_categorical(Y2)

<ipython-input-6-e0a94f0cba26>:5: FutureWarning: In a future version of pandas all arguments of DataFrame.any and Series.any will be keyword-only.
  db = db2[~db2.isin([np.inf]).any(1)]


(222040, 79) (222040,) (148027, 79) (148027,)


In [ ]:
#import gc
#del db1, db2, db3, db4, db5, db6, db7, db8, db, full_db, X, y, trainX1, trainY1, trainX, trainY, testX, testY
#gc.collect()

In [ ]:
# from collections import Counter
# from imblearn.under_sampling import RandomUnderSampler
# d = {0:1000, 1:500, 2:1000, 3:500, 4:1000, 5:500, 6:500, 7:500, 8:5, 9:10, 10:1000, 11:500, 12:500, 13:5, 14: 100}
# undersample = RandomUnderSampler(sampling_strategy=d)
# counter = Counter(trainY)
# print(counter)
# X, y = undersample.fit_resample(trainX, trainY)
# counter = Counter(y)
# print(counter)

In [ ]:
trainX = X
trainY = y

In [ ]:
def keras_cnn_model(X, Y):

    X_train_model = X
    Y_train_model = Y
    model = Sequential()
    model.add(Conv1D(filters=50, kernel_size=3, activation='Softmax', input_shape=(X_train_model.shape[1], X_train_model.shape[2]), kernel_initializer='random_uniform', bias_initializer='zeros'))
    # model.add(Dropout(0.5))
    # model.add(MaxPooling1D(pool_size=2))
    # model.add(Conv1D(filters=50, kernel_size=3, activation='relu'))
    # model.add(Dropout(0.5))
    model.add(Flatten())
    # model.add(Dense(100, activation='relu'))
    model.add(Dense(Y_train_model.shape[1], activation='softmax',kernel_initializer='random_uniform', bias_initializer='zeros'))
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    model.summary()
    return model

def keras_cnn_fit(model, X, Y, X1, Y1, epochs, batch_size):
    history = model.fit(X, Y, epochs=epochs, batch_size=batch_size, verbose = 1, validation_data=(X1, Y1))
    return history

def plot_keras_cnn(history):

    plt.plot(history.history['acc'])
    plt.plot(history.history['val_acc'])
    plt.title('model accuracy')
    plt.ylabel('accuracy')
    plt.xlabel('epoch')
    plt.legend(['train', 'test'], loc='upper left')
    plt.show()
    # summarize history for loss
    plt.plot(history.history['loss'])
    plt.plot(history.history['val_loss'])
    plt.title('model loss')
    plt.ylabel('loss')
    plt.xlabel('epoch')
    plt.legend(['train', 'test'], loc='upper left')
    plt.show()

In [ ]:
start_time = time.time()
modelCnn = keras_cnn_model(X1, Y1)
histCnn = keras_cnn_fit(modelCnn, X1, Y1, X2, Y2, 20, 256)
end_time = time.time()
elapsed_time = end_time - start_time

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv1d (Conv1D)             (None, 77, 50)            200       
                                                                 
 flatten (Flatten)           (None, 3850)              0         
                                                                 
 dense (Dense)               (None, 5)                 19255     
                                                                 
Total params: 19,455
Trainable params: 19,455
Non-trainable params: 0
_________________________________________________________________
Epoch 1/20
868/868 [==============================] - 12s 13ms/step - loss: 0.7721 - accuracy: 0.7254 - val_loss: 0.2163 - val_accuracy: 0.9767
Epoch 2/20
868/868 [==============================] - 11s 12ms/step - loss: 0.0968 - accuracy: 0.9904 - val_loss: 0.0330 - val_accuracy: 0.9968
Epoch 3/20
868/868 [========

In [ ]:
# predictions = modelCnn.predict(X2)

# predictions2 = np.argmax(predictions, axis=1)
# Y22 = np.argmax(Y2, axis=1)
# Y22.shape, predictions2.shape

# cm = confusion_matrix(Y22, predictions2)
# correct_pred = (Y22 == predictions2)
# acc = correct_pred.sum() / len(correct_pred)
# print(cm)
# print("Acc: ", acc*100)
# print(classification_report(Y22, predictions2,digits=5))

In [ ]:
# Start the timer
# start_time = time.time()

predictions = modelCnn.predict(X2)

predictions2 = np.argmax(predictions, axis=1)
Y22 = np.argmax(Y2, axis=1)
Y22.shape, predictions2.shape

cm = confusion_matrix(Y22, predictions2)
correct_pred = (Y22 == predictions2)
acc = correct_pred.sum() / len(correct_pred)

# End the timer and calculate the elapsed time
# end_time = time.time()
# elapsed_time = end_time - start_time
# elapsed_time_minutes = elapsed_time / 60  # Convert seconds to minutes

print(cm)
print("Acc: ", acc*100)
print(classification_report(Y22, predictions2, digits=5))
print("Training time: {:.2f} seconds".format(elapsed_time))







4626/4626 [==============================] - 11s 2ms/step
[[20199     5     0     0     0]
 [    0 50297     3     0     0]
 [    1    20 56969     0     1]
 [    0     1     0   491     0]
 [    0    10     0     0 20030]]
Acc:  99.9723023502469
              precision    recall  f1-score   support

           0    0.99995   0.99975   0.99985     20204
           1    0.99928   0.99994   0.99961     50300
           2    0.99995   0.99961   0.99978     56991
           3    1.00000   0.99797   0.99898       492
           4    0.99995   0.99950   0.99973     20040

    accuracy                        0.99972    148027
   macro avg    0.99983   0.99936   0.99959    148027
weighted avg    0.99972   0.99972   0.99972    148027

Training time: 223.98 seconds
