<a href="https://colab.research.google.com/github/Abdul-muizz/Abdul-Muizz.github.io/blob/main/CNN_RGK.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import datetime
import pandas as pd
from sklearn import tree
import time
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn import svm
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
import numpy as np
from sklearn import preprocessing
import sklearn as sk
from sklearn.linear_model import LogisticRegression
import os
from sklearn.model_selection import train_test_split

from sklearn.linear_model import SGDClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline

from numpy import loadtxt
from keras.models import Sequential
from keras.layers import Dense

import numpy as np
import pandas as pd

from keras.models import Model, Sequential
from keras.callbacks import EarlyStopping, ModelCheckpoint
from keras.layers import Dense, Input, LSTM, Embedding, Dropout, Activation
from keras import utils as np_utils
from keras.layers.merge import concatenate
#from keras.layers.normalization import BatchNormalization
from keras.preprocessing import sequence
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.layers import Conv1D, MaxPooling1D, Flatten, Reshape
import matplotlib.pyplot as plt

from keras.layers.wrappers import TimeDistributed

import keras
from sklearn import preprocessing
import tensorflow as tf
from sklearn.metrics import plot_confusion_matrix
from sklearn.metrics import multilabel_confusion_matrix
from sklearn.metrics import confusion_matrix
from sklearn.ensemble import RandomForestClassifier

import imblearn
from imblearn.under_sampling import RandomUnderSampler

import random
import tensorflow as tf
from imblearn.over_sampling import SMOTE
from torch.utils.data import Dataset, DataLoader, WeightedRandomSampler
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torch
from sklearn.metrics import classification_report, cohen_kappa_score
from sklearn.metrics import precision_score, recall_score, f1_score

from google.colab import drive
drive.mount('/content/drive')
%cd /content/drive/MyDrive/CICIDS2017/
!pwd

Mounted at /content/drive
/content/drive/MyDrive/CICIDS2017
/content/drive/MyDrive/CICIDS2017


In [ ]:
#db1 = pd.read_csv('Monday-WorkingHours.csv', sep=',')
db2 = pd.read_csv('Tuesday-WorkingHours.csv', sep=',')
#db3 = pd.read_csv('Wednesday-workingHours.pcap_ISCX.csv', sep=',')
#db4 = pd.read_csv('Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv', sep=',')
#db4 = pd.read_csv('Thursday-WorkingHours.csv', sep=',')
#db5 = pd.read_csv('Friday-WorkingHours.csv', sep=',')
#db7 = pd.read_csv('Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv', sep=',')
#db8 = pd.read_csv('Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv', sep=',')
#full_db = pd.concat([db1, db2, db3, db4, db5, db6, db7, db8])

#print(full_db.shape, full_db[' Label'].value_counts())
#print(100*full_db[' Label'].value_counts(normalize=True))
print(db2.shape, db2['Label'].value_counts())
print(100*db2['Label'].value_counts(normalize=True))

(322003, 84) BENIGN                     315031
FTP-Patator                  3973
SSH-Patator                  2980
FTP-Patator - Attempted        11
SSH-Patator - Attempted         8
Name: Label, dtype: int64
BENIGN                     97.834803
FTP-Patator                 1.233839
SSH-Patator                 0.925457
FTP-Patator - Attempted     0.003416
SSH-Patator - Attempted     0.002484
Name: Label, dtype: float64


In [ ]:
min_max_scaler = MinMaxScaler() 
le = preprocessing.LabelEncoder()

# db = full_db (for now we are usind db2)
db = db2[~db2.isin([np.inf]).any(1)]
df = db
#df = pd.DataFrame(db)
#df.drop(['Flow ID'], axis = 1)
#df.drop(['Src IP'], axis = 1)
#df.drop(['Dst IP'], axis = 1)
#df.drop(['Timestamp'], axis = 1)
del df['Flow ID'], df['Src IP'], df['Dst IP'], df['Timestamp']
#print(df.dtypes)
X, y = df.iloc[:, :-1], df.iloc[:, -1]

trainX1, testX, trainY1, testY = train_test_split(X, y, test_size=0.2, random_state=42)

trainY1=le.fit_transform(trainY1.to_numpy()).astype('int')
testY=le.fit_transform(testY.to_numpy()).astype('int')

trainX1 = min_max_scaler.fit_transform(trainX1)
testX = min_max_scaler.fit_transform(testX)

print(trainX1.shape, trainY1.shape, testX.shape, testY.shape)
trainX, trainY = trainX1, trainY1

X1 = np.reshape(trainX, (trainX.shape[0], trainX.shape[1], 1))
X2 = np.reshape(testX, (testX.shape[0], testX.shape[1], 1))
Y1 = np.reshape(trainY, (trainY.shape[0], 1))
Y1 = tf.keras.utils.to_categorical(Y1)
Y2 = np.reshape(testY, (testY.shape[0], 1))
Y2 = tf.keras.utils.to_categorical(Y2)

(257584, 79) (257584,) (64396, 79) (64396,)


In [ ]:
#import gc
#del db1, db2, db3, db4, db5, db6, db7, db8, db, full_db, X, y, trainX1, trainY1, trainX, trainY, testX, testY
#gc.collect()

In [ ]:
# from collections import Counter
# from imblearn.under_sampling import RandomUnderSampler
# d = {0:1000, 1:500, 2:1000, 3:500, 4:1000, 5:500, 6:500, 7:500, 8:5, 9:10, 10:1000, 11:500, 12:500, 13:5, 14: 100}
# undersample = RandomUnderSampler(sampling_strategy=d)
# counter = Counter(trainY)
# print(counter)
# X, y = undersample.fit_resample(trainX, trainY)
# counter = Counter(y)
# print(counter)

In [ ]:
trainX = X
trainY = y

In [ ]:
def keras_cnn_model(X, Y):

    X_train_model = X
    Y_train_model = Y
    model = Sequential()
    model.add(Conv1D(filters=50, kernel_size=3, activation='softmax', input_shape=(X_train_model.shape[1], X_train_model.shape[2]), kernel_initializer='random_uniform', bias_initializer='zeros'))
    # model.add(Dropout(0.5))
    # model.add(Conv1D(filters=50, kernel_size=3, activation='softmax'))
    # model.add(Dropout(0.5))
    # model.add(MaxPooling1D(pool_size=2))
    model.add(Flatten())
    # model.add(Dense(100, activation='softmax'))
    model.add(Dense(Y_train_model.shape[1], activation='softmax', kernel_initializer='random_uniform', bias_initializer='zeros'))
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    model.summary()
    return model

def keras_cnn_fit(model, X, Y, X1, Y1, epochs, batch_size):
    history = model.fit(X, Y, epochs=epochs, batch_size=batch_size, verbose = 1, validation_data=(X1, Y1))
    return history

def plot_keras_cnn(history):

    plt.plot(history.history['acc'])
    plt.plot(history.history['val_acc'])
    plt.title('model accuracy')
    plt.ylabel('accuracy')
    plt.xlabel('epoch')
    plt.legend(['train', 'test'], loc='upper left')
    plt.show()
    # summarize history for loss
    plt.plot(history.history['loss'])
    plt.plot(history.history['val_loss'])
    plt.title('model loss')
    plt.ylabel('loss')
    plt.xlabel('epoch')
    plt.legend(['train', 'test'], loc='upper left')
    plt.show()

In [ ]:
modelCnn = keras_cnn_model(X1, Y1)
histCnn = keras_cnn_fit(modelCnn, X1, Y1, X2, Y2, 10, 256)

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv1d (Conv1D)             (None, 77, 50)            200       
                                                                 
 flatten (Flatten)           (None, 3850)              0         
                                                                 
 dense (Dense)               (None, 5)                 19255     
                                                                 
Total params: 19,455
Trainable params: 19,455
Non-trainable params: 0
_________________________________________________________________
Epoch 1/10
1007/1007 [==============================] - 23s 22ms/step - loss: 0.1366 - accuracy: 0.9772 - val_loss: 0.1069 - val_accuracy: 0.9791
Epoch 2/10
1007/1007 [==============================] - 19s 19ms/step - loss: 0.0793 - accuracy: 0.9782 - val_loss: 0.0590 - val_accuracy: 0.9791
Epoch 3/10
1007/1007 [==

In [ ]:
predictions = modelCnn.predict(X2)

predictions2 = np.argmax(predictions, axis=1)
Y22 = np.argmax(Y2, axis=1)
Y22.shape, predictions2.shape

cm = confusion_matrix(Y22, predictions2)
correct_pred = (Y22 == predictions2)
acc = correct_pred.sum() / len(correct_pred)
print(cm)
print("Acc: ", acc*100)
print(classification_report(Y22, predictions2))

[[62503   461     0    87     0]
 [    0   761     0     0     0]
 [    4     0     0     0     0]
 [    2     3     0   574     0]
 [    1     0     0     0     0]]
Acc:  99.13348655195975
              precision    recall  f1-score   support

           0       1.00      0.99      1.00     63051
           1       0.62      1.00      0.77       761
           2       0.00      0.00      0.00         4
           3       0.87      0.99      0.93       579
           4       0.00      0.00      0.00         1

    accuracy                           0.99     64396
   macro avg       0.50      0.60      0.54     64396
weighted avg       0.99      0.99      0.99     64396



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
